
create module.dart to show the list of modules a user currently has. Each topic will be represented as a card with an image, title, and description. Tapping on a card will navigate to the topic details page. refer to database/study.sql to see the fields for the modules table. users can also create a new module by tapping on a floating action button that will open a form to input the module details and upload an image. the form will also have a field to input the subtopics or lessons included in the module. once the form is submitted, the new module will be added to the user's list of modules and can be accessed from the module page.

create module_detail.dart to show the details of a specific module. This page will display the module's image, title, description, and a list of subtopics or lessons included in the module. 

create topic.dart to represent topics which are basically the same as modules but not uploaded by the user. These will be used for the study and arena where users can select from a list of available topics to study. users are also able to create a topic by telling the chatbot what they want to learn and the chatbot will generate a topic for them. 

create chatbot.dart to ask the user what topic they want to learn and generate a topic for them. The chatbot will use the same topic model as the topics that are uploaded by users. The chatbot will also be able to generate subtopics and lessons for the generated topic. this topic will then be added to the user's list of modules and can be accessed from the module page.

create pve_menu.dart to show the list of available modules/topics for the user to train on. This page will display a list of topics with their images, titles, and descriptions sorted bypopularity among users and category. Tapping on a topic will navigate to the training page for that topic in pve.dart. modules and topics are separated. there is also a chatbot in this page at the top that the user can interact with to generate a topic for them to train on. the generated topic will then be added to the list of available topics for the user to select from. generated topics are modules. 

in arena.dart, instead of just one battle button, divide it into ranked and quickmatch which lead to screens/arena/pvp_ranked.dart and screens/arena/pvp_quickmatch.dart respectively. preserve the styling. underneath the battle buttons are a daily popular topics section. also the background gets cut off at the top nav bar, make it full bleed.

create pve.dart to show a battle between the user and a boss pokemon. The user will be able to select a topic/module to train on and the boss pokemon will ask questions related to that topic. The user will have to answer the questions correctly to defeat the boss pokemon. The user will earn rewards for defeating the boss pokemon and can use those rewards to upgrade their pokemon or buy new items in the shop. use widgets/arena/question.dart to show the questions and options for the user to select from. use widgets/arena/pokemon_sprite.dart to show the boss pokemon and the user's pokemon. use widgets/arena/boss_sprite.dart to show the boss pokemon. refer to the stats in the pokemon model to determine the difficulty of the questions and the rewards for defeating the boss pokemon. the user's pokemon will also have stats that can be upgraded using the rewards earned from defeating boss pokemon. the user's pokemon will also have a type that can be used to determine the effectiveness of the user's attacks against the boss pokemon. the boss pokemon will also have a type that can be used to determine the effectiveness of the boss pokemon's attacks against the user's pokemon. use a turn-based battle system where the user and the boss pokemon take turns attacking each other until one of them is defeated. this screen should force the phone into landscape mode. 


create pvp_quickmatch.dart to show a battle between the user and another user. The user will be able to select a topic/module to train on and the other user will also select a topic/module to train on. The two users will then battle each other by answering questions related to their selected topics. The user who answers the most questions correctly will win the battle. The user will earn rewards for winning the battle and can use those rewards to upgrade their pokemon or buy new items in the shop. use widgets/arena/question.dart to show the questions and options for the users to select from. use widgets/arena/pokemon_sprite.dart to show the user's pokemon and the other user's pokemon. refer to the stats in the pokemon model to determine the difficulty of the questions and the rewards for winning the battle. the user's pokemon will also have stats that can be upgraded using the rewards earned from winning battles. the user's pokemon will also have a type that can be used to determine the effectiveness of the user's attacks against the other user's pokemon. the other user's pokemon will also have a type that can be used to determine the effectiveness of their attacks against the user's pokemon. use a turn-based battle system where the two users take turns attacking each other until one of them is defeated. this screen should force the phone into landscape mode.

create pvp_ranked.dart to show a battle between the user and another user in a ranked match. the only difference in ranked match tahn quickmatch is that the topic is a random topic from the database. the topic will be shown upon game load.  


create an sql patch for topics or anything else needed to be added to the database put it in dataase/patch.sql, and update database/study.sql to include the new tables and fields needed for the topics.

make lib/screens/inventory/pokemons.dart edit teams functional and showo only the pokemons in the users database.
